### PR TITLE
Fix #44 and fix the delivery options parsing.

### LINKED ISSUE #44: RECIPIENT_FAILURE missing for bridge client consumers
### Version

* vert.x core: 3.6.0.CR1
* vert.x tcp eventbus bridge: 3.6.0.CR1

Missing common event bus failure handling for consumers placed on bridge clients. There is no way to get a ReplyException on a server-side sender in the case of a recipient failure on a bridge client consumer.

### PR DESCRIPTION
**Pull request by EddieParis**

### CODE REVIEW

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java [hunk 1]
```diff
@@ -210,6 +210,39 @@ public void testSendMessageWithReplyBacktrack(TestContext context) {
...
+  @Test
+  public void testSendMessageWithReplyBacktrackTimeout(TestContext context) {
+    // Send a request and get a response
+    NetClient client = vertx.createNetClient();
+    final Async async = context.async();
+
+    // This does not reply and will provoke a timeout
+    vertx.eventBus().consumer("test", (Message<JsonObject> msg) -> { /* Nothing! */ } );
+
+    client.connect(7000, "localhost", conn -> {
```
Comment (vietj) [inline src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: use ctx.asyncAssertSuccess instead that avoids the `context.assertFalse(conn.failed())`

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java [hunk 2]
```diff
@@ -319,6 +352,86 @@ public void testUnRegister(TestContext context) {
...
+    // Send a request from java and get a response from the client
+    NetClient client = vertx.createNetClient();
+    final Async async = context.async();
+    final String address = "test";
+    client.connect(7000, "localhost", conn -> {
+      context.assertFalse(conn.failed());
+
+      NetSocket socket = conn.result();
+
+      final FrameParser parser = new FrameParser(parse -> {
```
Comment (vietj) [inline src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: use `context.assertAsyncSuccess` instead

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java [hunk 3]
```diff
@@ -319,6 +352,86 @@ public void testUnRegister(TestContext context) {
...
+        }
+      });
+
+      socket.handler(parser);
+
+      FrameHelper.sendFrame("register", address, null, socket);
+
+      // There is now way to know that the register actually happened, wait a bit before sending.
+      vertx.setTimer( 500L, timerId -> {
+          vertx.eventBus().send(address, new JsonObject().put("value", "Vert.x"), (AsyncResult<Message<JsonObject>> respMessage) -> {
```
Comment (vietj) [inline src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: use this instead on send generic instead of cast : `eventBus().<JsonObject>send(...)`

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java [hunk 4]
```diff
@@ -319,6 +352,86 @@ public void testUnRegister(TestContext context) {
...
+              context.assertTrue(respMessage.succeeded());
```
Comment (vietj) [inline src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: use instead `context.assertAsyncSuccess(...)`

**Comment by vietj** [comment]
I've done a couple of comments for review, it shall be merged in 3.7

**Comment by vietj** [comment]
@EddieParis can you address the minor PR concerns before we can merge it ?

**Comment by vietj** [comment]
fixes https://github.com/vert-x3/vertx-tcp-eventbus-bridge/issues/44

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java (hunk 1 above)
Comment (oortigues-verimatrix) [reply src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: Done, and everywhere else in this file, I did the modification.

File: src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java (hunk 2 above)
Comment (EddieParis) [reply src/test/java/io/vertx/ext/eventbus/bridge/tcp/TcpEventBusBridgeTest.java]: Done, and everywhere else it appeared in this file, I did the modification.

**Comment by vietj** [comment]
@pmlopes can you review this PR ? I want to be sure it is correct protocol wise

**Comment by vietj** [comment]
thanks for the contribution and the review!
