### PR TITLE
Fixes #10 and #11: complies to the reproducer and passes

### LINKED ISSUE #10: Reply not being sent in a clustered environment
### Version

* vert.x core: 3.2.1
* vert.x tcp eventbus bridge: 3.2.1

### Context

I have a vert.x 2 project communicating to a vert.x 3 project through the event bus. The vert.x 2 uses the [EventBus3](https://github.com/vert-x/mod-eventbus3-bridge-client/tree/initial-work) and vert.x 3 uses the tcp eventbus bridge.
If the vert.x 3 isn't clustered it works fine, however when deployed in a cluster things go bad. I have a "machine" that just has one Verticle that creates the bridge, and several other machines with my application logic. When I send a message to the EventBus from my app servers, it is caught by the Bridge, sent to vert.x 2, vert.x 2 sends it back to the bridge but the bridge never sends it back to the app original app server.

tcp bridge issue

I looked into the source, and IMO the issue is that when the bridge receives a send event, it then does `eventbus.send(address, ...)` and doesn't consider if it's a response message or not. Locally this works because doing `eventbus.send(replyAddress, ...)` is equivalent to `message.reply(...)` (or very similar in the way it works) but in a clustered environment the behaviour differs and thus doing `eventbus.send(replyAddress, ...)` does not work.

Ideas to solve this : 
* when a message is sent through the bridge store the `Message` in a map(reply_address, original_message) in order to get it back on the reply from the exterior app, and do `message.reply(...)`

### LINKED ISSUE #11: "headers" always empty
### Version

* vert.x core: 3.2.1
* vert.x tcp eventbus bridge: 3.2.1

### Context

The tcp eventbus bridge always returns empty "headers" 

#### Socket client (input) :

```javascript
{
  "type" : "send",
  "headers" : {
    "action" : "findAll"
  },
  "body" : {
    "model" : "news"
  },
  "address" : "io.vertx",
  "replyAddress" : "io.vertx"
}
```

#### Socket client (output) :

```javascript
{
  "type" : "message",
  "address" : "io.vertx",
  "headers" : { },
  "body" : {
    "model" : "news"
  }
}
```

### PR DESCRIPTION
**Pull request by pmlopes**
Fixes #10 
Fixes #11 

Delivers replies across the cluster
The reproducer passes

### CODE REVIEW

File: src/main/java/io/vertx/ext/eventbus/bridge/tcp/impl/TcpEventBusBridgeImpl.java [hunk 1]
```diff
@@ -124,7 +125,8 @@ public TcpEventBusBridge listen(int port, Handler<AsyncResult<TcpEventBusBridge>
 
   private void handler(NetSocket socket) {
 
-    final Map<String, MessageConsumer<?>> registry = new HashMap<>();
+    final Map<String, MessageConsumer<?>> registry = new ConcurrentHashMap<>();
+    final Map<String, Message<JsonObject>> replies = new ConcurrentHashMap<>();
```
Comment (LuisGioanni) [inline src/main/java/io/vertx/ext/eventbus/bridge/tcp/impl/TcpEventBusBridgeImpl.java]: I'm not a Vert.x expert, but i have a concern : in the case where we have multiple instances, say instance A sends the message through the NetServer and stores the message in the `replies` map, the NetClient that receives this message will eventually send a new message to the NetServer, this message can be processed by instance B, which will have a different `replies` map.
Like I said, i'm no expert, I may be completely wrong, and if I am could you enlighten my concerns.

Comment (pmlopes) [inline src/main/java/io/vertx/ext/eventbus/bridge/tcp/impl/TcpEventBusBridgeImpl.java]: The map is in the netsocket handler so it is per connection, replies should only be called once, so even if the message is sent to various clients they won't overwrite each other.

**Comment by vietj** [comment]
looks good to me
